server:
  port: 8082

spring:
  application:
    name: seat-order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seat-order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123

  cloud:
    consul:
      host: 192.168.7.33
      port: 8500
      config:
        format: yaml
      discovery:
        serviceName: ${spring.application.name}
        # 健康检查地址使用ip
        prefer-ip-address: true
        # 实例名
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

    alibaba:
      seata:
        tx-service-group: etmpro

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

